apiVersion: v1
kind: Service
metadata:
  name: emobile-song-db-service
  labels:
    name: emobile-song-db-service
spec:
  type: ClusterIP
  selector:
    app: emobile-song-db
  ports:
    - name: tcp-portC
      protocol: TCP
      port: 5435
      targetPort: song-db-port
