apiVersion: apps/v1
kind: Deployment
metadata:
  name: emobile-song-app-deployment
  labels:
    app: emobile-song-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: emobile-song-app
  template:
    metadata:
      labels:
        app: emobile-song-app
    spec:
      containers:
        - name: emobile-song-app
          image: obuhovskaia11/emobile-song:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: song-app-port
          envFrom:
            - configMapRef:
                name: emobile-song-app-config
      restartPolicy: Always