apiVersion: v1
kind: Service
metadata:
  name: emobile-song-app-service
  labels:
    name: emobile-song-app-service
spec:
  type: NodePort
  selector:
    app: emobile-song-app
  ports:
    - name: tcp-port
      protocol: TCP
      port: 80
      targetPort: song-app-port
      nodePort: 30080
