apiVersion: v1
kind: ConfigMap
metadata:
  name: emobile-song-app-config
  namespace: default
data:
  APP_PORT: "80"
  APP_LOG_LEVEL: "debug"
  APP_ENABLE_SWAG: "true"
  APP_HOST: "0.0.0.0"
  APP_EXTERNAL_HOST: "node_external_ip"
  APP_EXTERNAL_PORT: "30080"
  APP_INFO_SERVICE_URL: "http://localhost:8088/info"
  APP_PAG_LIMIT: "50"

  POSTGRES_USER: "user1"
  POSTGRES_PASSWORD: "1234"
  POSTGRES_HOST: "emobile-song-db-service"
  POSTGRES_PORT: "5435"
  POSTGRES_DB: "postgres"
  POSTGRES_MIGRATION: "file://migration"